version: '3'

services:

  app:
    build: .
    tty: true
    command: >
      sh -c "python manage.py makemigrations &&
         python manage.py migrate &&
         python manage.py csu &&
         python manage.py loaddata tracker.json &&
         python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - celery_beat

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis